/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ivan Norman (https://sketchfab.com/vanidza)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-university-a68d0b72205b49849ed1e6d6c3851749
Title: Low-poly university
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
const University = (props) => {
  const universityRef = useRef();
  useGSAP(() => {
    gsap.to(universityRef.current.position, {
      y: universityRef.current.position.y + 0.1,
      z: universityRef.current.position.z + 0.1,
      duration: 1.5,
      repeat: -1,
      yoyo: true,
    });
  });
  useGSAP(() => {
    gsap.to(universityRef.current.rotation, {
      y: universityRef.current.rotation.y + 0.2,
      duration: 1.5,
      repeat: -1,
      yoyo: true,
    });
  });

  const { nodes, materials } = useGLTF("/models/university.glb");
  return (
    <group {...props} dispose={null} ref={universityRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.School}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/models/university.glb");
export default University;
